In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('../data/train.txt', sep=';',header=None , names=['text','emotion'])

In [3]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [5]:
unique_emotions = df['emotion'].unique()

In [6]:
emotion_numners = {}
i = 0
for emo in unique_emotions:
    emotion_numners[emo] = i
    i += 1

In [7]:
emotion_numners

{'sadness': 0, 'anger': 1, 'love': 2, 'surprise': 3, 'fear': 4, 'joy': 5}

In [8]:
df['emotion'] = df['emotion'].map(emotion_numners)

In [9]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [10]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [11]:
import string

In [12]:
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [13]:
df['text']= df['text'].apply(remove_punc)

In [14]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

In [15]:
def remove_numbers(txt):
  new = ""
  for i in txt:
    if not i.isdigit():
      new = new+i
  return new

df['text'] = df['text'].apply(remove_numbers)

In [16]:

def remove_emoji(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_emoji)

In [18]:
import nltk

In [19]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [26]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Dell\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [27]:
stop_words = set(stopwords.words('english'))

In [28]:
def remove(txt):
  word_tokens = word_tokenize(txt)
  cleaned = []
  for i in word_tokens:
    if i not in stop_words:
      cleaned.append(i)
  return " ".join(cleaned)

In [29]:
df['text'] = df['text'].apply(remove)

In [30]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1